# Generated by Django 5.0.2 on 2024-02-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_file_id_alter_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
